server:
  port: 80
  base-path: mpu-cash-in-exp

#mybatis:
#  mapper-locations: "**/*Mapper.xml"
#  configuration:
#    jdbc-type-for-null: 'NULL'

spring:
  profiles:
    include: >
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:h2:file:./data/wave_hackathon
    jdbc-url: jdbc:h2:file:./data/wave_hackathon
    username: root
    password:
    driver-class-name: org.h2.Driver
    dbSchema: waveMerchant
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true


authentication:
  h2:
    console:
      enabled: true
  datasource:


mybatis:
#  mapper-locations: classpath*:mybatis/*.xml